### ISSUE TITLE
I have issue - _GiphySDK.NativeGiphySDK is undefined

### ISSUE THREAD

**Issue by Rananjaya** [Giphy/giphy-react-native-sdk#73] opened 2022-08-24 13:59 UTC
I have this issue when using giphy react native sdk...

_GiphySDK.NativeGiphySDK is undefined

**Comment by Rananjaya** [comment] 2022-08-25 14:44
Hi @pshoniuk  Im using  "react-native": "~0.63.4" for my project and im tested it on android 9.0.

**Comment by pshoniuk** [comment] 2022-09-06 13:03
@Rananjaya I have not been able to reproduce this. If the problem is still relevant, could you please create and share a minimal playground where this problem occurs?

**Comment by pshoniuk** [comment] 2022-09-28 07:51
I am going to close this issue. Please reopen it or open a new one if it is still relevant and you have additional details.

**Closed by pshoniuk** 2022-09-28 07:51 UTC
Labels: bug

**Comment by Rananjaya** [comment] 2022-10-04 07:35
any solution for this ?
