### ISSUE TITLE
Error with configuring api key

### ISSUE THREAD

**Issue by vishwak5599** [Giphy/giphy-react-native-sdk#151] opened 2023-10-22 05:37 UTC
If i add 
import { GiphySDK } from '@giphy/react-native-sdk'

GiphySDK.configure({
  apiKey: '*************', // Android SDK key
})

this code bloack to my code iam getting the below error :

ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RTNGiphySDKModule' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes

Please help!!

**Comment by pshoniuk** [comment] 2023-10-23 12:54
Hi @vishwak5599  
Could you please provide more details, like React Native & GIPHY RN SDK versions and whether the new or old arch is used? It would be ideal if you could share a minimal reproducer repo.

**Comment by pshoniuk** [comment] 2023-10-26 06:34
Duplicate of https://github.com/Giphy/giphy-react-native-sdk/issues/153

**Closed by pshoniuk** 2023-10-26 06:34 UTC
Labels: duplicate
