### ISSUE TITLE
GIPHY rating not working when using GiphyDialog.configure to specify ratings

### ISSUE THREAD

**Issue by sounritesh** [Giphy/giphy-react-native-sdk#74] opened 2022-08-30 11:48 UTC
## 🐛 Bug Report

I am getting the same results (which are inappropriate) when setting the rating as 'g', 'r', 'pg' etc. on searching profane words. I am using the GiphyDialog.configure method to set the rating parameter.

## To Reproduce

Step 1: Configure Giphy SDK as described in the quick use guide
Step 2: Configure GiphyDialog using GiphyDialog.configure and set rating as 'g' (basic level 1, ideally no profane content should appear)
Step 3: Search profane words in the app dialog
Step 4: Change the rating to 'r' in the configuration
Step 5: Search the same profane words as done previously
Step 6: You will notice the same inappropriate results in both the cases

## Expected behavior
No profane/NSFW should be visible when rating is set to 'g'

## Actual Behavior
Same content (profane/NSFW in nature) is visible for all ratings.

## Environment

- Giphy React Native SDK version: 1.9.0
- React Native version: 0.68.2
- Platform(s): Android (Emulator as well as physical device)

**Comment by pshoniuk** [comment] 2022-08-30 13:08
Hey @sounritesh, thanks for reaching out.

I was unable to reproduce this. I searched for profanity words with different ratings and got different search results that matched the given rating. Examples of my configurations:
- `GiphyDialog.configure({ rating: GiphyRating.G })`
- `GiphyDialog.configure({ rating: GiphyRating.R })`

Please contact [support@giphy.com](mailto:support@giphy.com) if you see any content that you feel is incorrectly rated or in violation of GIPHY’s Community Guidelines. Also, feel free to reach out if you have any general questions about content safety at GIPHY as well.

**Comment by sounritesh** [comment] 2022-08-30 13:55
Hey @pshoniuk, this seems to work fine with the iOS simulator on Mac, however it is causing issues when run on an android emulator or physical android device. Hope you are able to recreate the bug when using Android as the platform.

**Comment by pshoniuk** [comment] 2022-08-30 14:58
Yeah, I reproduced it on the Android platform. A fix will be released in the next release

**Closed** 2022-08-31 07:51 UTC
Labels: bug

**Comment by pshoniuk** [comment] 2022-08-31 10:50
@sounritesh This issue should be fixed in version [v1.9.1](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v1.9.1). Please try this version when you have a chance.

**Comment by sounritesh** [comment] 2022-08-31 11:28
Thank you @pshoniuk, the issue is fixed in the new release.
