### ISSUE TITLE
GiphyGridView  showing black bar in Android for 'Recents' content type

### ISSUE THREAD

**Issue by Hyzam-Ali** [Giphy/giphy-react-native-sdk#41] opened 2021-11-25 06:43 UTC
In Android, when the 'content' prop of GiphyGridView is set to 'GiphyContent.recents()', it is rendering a black bar. It is working fine for iOS platform.

Steps to reproduce:
- Add a GiphyGridView to your View
- Set the content prop of GiphyGridView to GiphyContent.recents()
- Run the application for ios and Android
- Observation: the recent gifs are correctly rendered for iOS, while on Android it's rendering a black bar

**Comment by pshoniuk** [comment] 2021-11-25 08:24
Hi @Hyzam-Ali, thanks for the report!

Unfortunately, I can't reproduce this in my environment. Would you mind describing your environment (versions of Android SDK, React Native, etc.)? Also, it would be very helpful if you could provide a screenshot with this black bar.

**Comment by Hyzam-Ali** [comment] 2021-11-25 10:42
Android - Pixel 4 XL (Android 11)
iOS - iPhone 11 (iOS 15)

<img width="380" alt="recents-Android" src="https://user-images.githubusercontent.com/91958946/143426921-afa69a13-acbd-4cf2-9e38-7773164551a9.png">

**Comment by pshoniuk** [comment] 2021-11-25 14:10
@Hyzam-Ali I made a playground with the environment you described. But I couldn't reproduce this issue. Everything works for me.  Does this problem reproduce itself in [the example app](https://github.com/Giphy/giphy-react-native-sdk/tree/main/example)?

**Comment by Hyzam-Ali** [comment] 2021-11-29 07:59
> @Hyzam-Ali I made a playground with the environment you described. But I couldn't reproduce this issue. Everything works for me. Does this problem reproduce itself in [the example app](https://github.com/Giphy/giphy-react-native-sdk/tree/main/example)?

I am getting the same behaviour in Example app after making some changes in 'giphy-react-native-sdk/example/src/App.tsx'. Please refer the attached screenshots.

<img width="1706" alt="Screenshot 2021-11-29 at 1 25 08 PM" src="https://user-images.githubusercontent.com/91958946/143829193-782e52ad-dd4d-4be2-a587-80d32cddfbe2.png">
<img width="417" alt="Screenshot 2021-11-29 at 1 24 38 PM" src="https://user-images.githubusercontent.com/91958946/143829237-f2662110-ae4d-4a6f-8f6e-2c889d5d91da.png">

**Comment by pshoniuk** [comment] 2021-11-29 12:36
Yeah, I reproduced that too. It seems that on Android when the user selects gifs from the custom GiphyGridView, the latest gifs aren't displayed correctly. I've addressed this issue to the Giphy Android SDK team and will update the Giphy RN SDK and status here when this is fixed. Thank you for such a detailed report @Hyzam-Ali

**Comment by pshoniuk** [comment] 2021-12-01 11:46
This issue should be fixed in version [v1.2.0](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v1.2.0)

**Closed by pshoniuk** 2021-12-01 11:46 UTC
